title: "Manifest"
description: "Манифест управления сообществами METADATA."

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap

author:
  name: "Kitsune Solar"
  email: "kitsune.solar@gmail.com"
  github: "metacraft"
  twitter: "metadatafdn"